name: The Grecophone
favicon: null
layout_spectrum: 0.7067961357533932
typography_spectrum: 0.4485667268745601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7785256195347756
  lightness: 0.8151415167376399
  saturation: 0.1842349695507437
  rhythmicContrast: 0.9744421131908894
purpose: []
